version: 0.2
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - n install 18
  pre_build:
    commands:
      - npm --version
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build/'